export const UserActionTypes = {
  USER_PENDING: "USER_PENDING",
  USER_ERROR: "USER_ERROR",
  USER_RESET_ERROR: "USER_RESET_ERROR",
  USER_SET: "USER_SET",
  USER_SET_SETTINGS: "USER_SET_SETTINGS",
  USER_SET_LOCATION: "USER_SET_LOCATION",
  USER_RESET_LOCATION: "USER_RESET_LOCATION",
}
