const ActionTypes = {
  SET_OPEN: 'SET_OPEN',
  SET_CLOSE: 'SET_CLOSE',
  SET_PREV: 'SET_PREV',
  SET_NEXT: 'SET_NEXT',
  SET_INDEX: 'SET_INDEX',
  SET_INDEX_AND_OPEN: 'SET_INDEX_AND_OPEN',
  SET_IS_OPEN: 'SET_IS_OPEN',
}

export default ActionTypes
