const SUGGESTED = {
  Amazon: ['amazon'],
  Apple: ['apple'],
  Article: [
    'quora',
    'article',
    'medium',
    'forbes',
    'fox',
    'cnn',
    'nytimes',
    'express',
    'politic',
    'cbs',
    'theverge',
    'yahoo',
    'fortune',
    'post',
    'file',
  ],
  Cloud: ['doc', 'drive', 'aws', 'dropbox', 'cloud', 'box', 'file'],
  Development: [
    'app',
    'css',
    'react',
    'angular',
    'ionic',
    'vue',
    'material',
    'pwa',
    'code',
    'program',
  ],
  Document: ['doc', 'drive', 'aws', 'dropbox', 'cloud', 'box', 'file'],
  Dream: ['dream', 'vision'],
  Facebook: ['facebook'],
  Gaming: ['game', 'theverge'],
  Email: ['mail', 'message'],
  Image: ['<img src', 'instagram', 'pintrest', 'image', 'photo', 'file'],
  Instagram: ['instagram'],
  Twitter: ['twitter'],
  Link: ['http', '.com'],
  Review: ['yelp', 'review'],
  Shopping: ['amazon', 'bestbuy', 'lowes', 'shop', 'target', '$'],
  Support: ['support'],
  Text: ['text', 'message'],
  Video: ['youtube', '<iframe', 'file'],
  Vision: ['dream', 'vision'],
}

export { SUGGESTED }
