export const BasicTableActionTypes = {
  BASIC_TABLE_SORT: "BASIC_TABLE_SORT",
  BASIC_TABLE_FILTER: "BASIC_TABLE_FILTER",
  BASIC_TABLE_SET_PAGE: "BASIC_TABLE_SET_PAGE",
  BASIC_TABLE_SET_PAGE_SIZE: "BASIC_TABLE_SET_PAGE_SIZE",
}
