export const AdminActionTypes = {
  ADMIN_USERS_PENDING: "ADMIN_USERS_PENDING",
  ADMIN_SET_USERS: "ADMIN_SET_USERS",
  ADMIN_SET_USERS_ENTRIES: "ADMIN_SET_USERS_ENTRIES",
  ADMIN_SET_USER_ENTRIES_DETAILS: "ADMIN_SET_USER_ENTRIES_DETAILS",
  ADMIN_SET_USER_ENTRY: "ADMIN_SET_USER_ENTRY",
}
