export const AppActionTypes = {
  APP_SET_VERSION: 'APP_SET_VERSION',
  APP_SET_LOCAL_STORAGE_USAGE: 'APP_SET_LOCAL_STORAGE_USAGE',
  REDUX_RESET: 'REDUX_RESET',
  LOAD_PERSISTED_STATE_PENDING: 'LOAD_PERSISTED_STATE_PENDING',
  LOAD_PERSISTED_STATE: 'LOAD_PERSISTED_STATE',
}
