const CookieMap = {
  USER_TOKEN: "User_Token",
  USER_LAST_LOGIN: "User_Last_Login"
}

const SocialAuthenticationProviders = {
  FACEBOOK: "Facebook",
  GOOGLE: "Google"
}

const ReduxActions = {
  ALERTS_SET_MESSAGE: "ALERTS_SET_MESSAGE",
  ALERTS_CLEAR: "ALERTS_CLEAR",
  CALENDAR_SET: "CALENDAR_SET",
  USER_SET: "USER_SET",
  USER_SET_SETTINGS: "USER_SET_SETTINGS",

  SET_WINDOW: "SET_WINDOW",

  SET_USER_LOCATION: "SET_USER_LOCATION",

  TEXT_EDITOR_SET: "TEXT_EDITOR_SET",
  TEXT_EDITOR_CLEAR: "TEXT_EDITOR_CLEAR",

  ENTRIES_PENDING: "ENTRIES_PENDING",
  ENTRIES_ERROR: "ENTRIES_ERROR",
  ENTRIES_SET: "ENTRIES_SET",
  ENTRIES_SET_BY_DATE: "ENTRIES_SET_BY_DATE",
  ENTRY_IMPORT: "ENTRY_IMPORT",
  ENTRY_SET: "ENTRY_SET",
  ENTRY_POST: "ENTRY_POST",
  ENTRY_UPDATE: "ENTRY_UPDATE",
  ENTRY_UPDATE_IMAGE: "ENTRY_UPDATE_IMAGE",
  ENTRY_DELETE: "ENTRY_DELETE",

  ENTRIES_SEARCH_FILTER: "ENTRIES_SEARCH_FILTER",

  REDUX_PERSIST: "REDUX_PERSIST",
  REDUX_RESET: "REDUX_RESET"
}
export { CookieMap, SocialAuthenticationProviders, ReduxActions }
