export const EntriesActionTypes = {
  ENTRIES_SET_TAGS: "ENTRIES_SET_TAGS",
  ENTRIES_PENDING: "ENTRIES_PENDING",
  ENTRIES_ERROR: "ENTRIES_ERROR",
  ENTRIES_COMPLETE: "ENTRIES_COMPLETE",
  ENTRIES_SET: "ENTRIES_SET",
  ENTRIES_SET_BY_DATE: "ENTRIES_SET_BY_DATE",
  ENTRY_IMPORT: "ENTRY_IMPORT",
  ENTRY_SET: "ENTRY_SET",
  ENTRY_POST: "ENTRY_POST",
  ENTRY_UPDATE: "ENTRY_UPDATE",
  ENTRY_DELETE: "ENTRY_DELETE",
  ENTRIES_SEARCH_FILTER: "ENTRIES_SEARCH_FILTER"
}
